version: '3.2'
services:
  biomage-ingest:
    container_name: 'biomage-ingest'
    build:
      target: prod
      context: .
      args:
        - CLUSTER_ENV=${CLUSTER_ENV-staging}
    volumes:
      - ./src:/data-ingest/src:cached
      - ./input:/input:cached
      - ./output:/output:cached
      - ~/.aws:/root/.aws:cached